name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Store here https://github.com/santokhan/ssbanglaexpress/settings/secrets/actions
          VPS_USER: ${{ secrets.VPS_USER }} # Store here https://github.com/santokhan/ssbanglaexpress/settings/secrets/actions
          VPS_HOST: ${{ secrets.VPS_HOST }} # Store here https://github.com/santokhan/ssbanglaexpress/settings/secrets/actions
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -e "ssh -i private_key" -avz --exclude 'node_modules' --exclude '.git' ./ $VPS_USER@$VPS_HOST:/home/ubuntu/app/ssbanglaexpress/next
          ssh -i private_key $VPS_USER@$VPS_HOST "cd /home/ubuntu/app/ssbanglaexpress/next && npm install && npm run build && pm2 restart nextjs-app"
